#!/usr/bin/env bash

nth() {
    local -a lines
    mapfile -t lines
    (( ${#lines[@]} == 0 )) && return 1
    (( ${#lines[@]} == 1 )) && printf "%s\n" "${lines[0]#*$'\t'}" && return 0
    local idx=$(IFS=$'\n'; awk -F'\t' '{ print $1 ($3 ? " " $3 : ($2 ? " " $2 : "")) }' <<< "${lines[*]}" | fuzzel -d -p "$1" --index $menu_extra_flags)
    [[ -n "$idx" && "$idx" =~ ^[0-9]+$ ]] && printf "%s\n" "${lines[idx]#*$'\t'}"
}

die() {
    notify-send "anifuzz" "$*" -i dialog-error
    exit 1
}

hianime_curl() {
    curl -sL -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" --max-time 10 "$@"
}

b64_decode() {
    base64 -d <<< "$1" 2>/dev/null || base64 -D <<< "$1" 2>/dev/null || openssl base64 -d -A <<< "$1" 2>/dev/null
}

# search the query and give results. format is (id \t name)
hianime_search() {
    _page="$(hianime_curl "https://hianime.at/search?keyword=$1")"
    [[ "${_page,,}" == *"<title>just a moment"* ]] && die "Blocked by cloudflare."
    <<<"$_page" awk -v RS='<a href="https://hianime.at/watch/' '
        /^[^"]+"/ && match($0, /title="[^"]+"/) {
            title = substr($0, RSTART + 7, RLENGTH - 8);
            gsub(/&#039;/, "\047", title);
            gsub(/&quot;/, "\"", title);
            gsub(/&amp;/, "\\&", title);
            sub(/".*/, "", $0);
            if ($0 ~ /^[a-zA-Z0-9-]+$/) print $0 "\t" title;
        }
        /id="main-sidebar"/ { exit }
    '
}

# get the episodes list of the selected anime. format is (id \t ep_no)
hianime_episodes() {
    hianime_curl "https://hianime.at/api/theme/episode/list/${1##*-}" | awk -v RS='ep-item' -v slug="$1" '
        { gsub(/\\/, "") }
        $0 ~ ("/watch/" slug "[?]ep=") && match($0, /data-id="[0-9]+"/) {
            printf "%s\t", substr($0, RSTART + 9, RLENGTH - 10);
            match($0, /data-number="[^"]*"/);
            print substr($0, RSTART + 13, RLENGTH - 14);
        }
    '
}

# extract the individual m3u8 links from response of embed urls
hianime_m3u8() {
    _embed="$(b64_decode "$(hianime_curl "https://hianime.at/api/theme/episode/servers?episodeId=$(awk -F'\t' -v ep="$1" '$2 == ep {print $1; exit}' <<<"$episode_maps")" | awk -v type="$2" -v RS='server-item' '
        {
            gsub(/\\"/, "\"");
        }
        index($0, "data-type=\"" type "\"") > 0 && /data-server-name="ZokoAnime"/ && match($0, /data-hash="[^"]*"/) {
            print substr($0, RSTART + 11, RLENGTH - 12);
            exit;
        }
    ')")"
    [[ -z "$_embed" ]] && return 1
    IFS=/ read -r p1 p2 p3 _ <<< "$_embed"
    refr="$p1//$p3/"
    local key=(111 116 97 107 117 45 101 109 98 101 100 45 118 49) _json_raw="" i=0 _char
    for _byte in $(b64_decode "$(hianime_curl "$_embed" | awk '/window\.__P="/{
    	sub(/.*window\.__P="/, "");
    	sub(/".*/, "");
    	print;
    	exit
    }
    ')" | od -v -An -tu1); do
        _char=$((_byte ^ key[i++ % 14]))
        _json_raw+=\\0$((_char / 64))$(((_char / 8) % 8))$((_char % 8))
    done
    eval "$(printf "%b" "$_json_raw" | awk '
        match($0, /"src":"[^"]*\.m3u8"/) { v = substr($0, RSTART + 7, RLENGTH - 8) }
        /"default":true/ { 
        	tmp = $0; sub(/.*"default":true/, "", tmp);
        	if (match(tmp, /"src":"[^"]*"/)) s = substr(tmp, RSTART + 7, RLENGTH - 8)
        }
        END { print "video_link=\"" v "\"\nsub_link=\"" s "\"" }
    ')"
    [[ -n "$video_link" ]] || return 1
}

update_history() {
    local tmp_hist="${histfile}.$$"
    if awk -F'\t' -v ep="$ep_no" -v id="$anime_id" -v title="$anime_title" '
        BEGIN { OFS="\t" }
        $2 == id {
            $1 = ep;
            $3 = title;
            found=1;
        }
        1
        END { if (!found) print ep, id, title }
    ' "$histfile" > "$tmp_hist"; then
        mv "$tmp_hist" "$histfile"
    else
        rm -f "$tmp_hist"
    fi
}

play() {
    # In case a range (e.g. 5-10) or multi-select was passed, just grab the first episode
    ep_no="${ep_no%%[ -]*}"
    [[ -z "$ep_no" ]] && ep_no="${ep_list%%$'\n'*}"
    [[ $'\n'"$ep_list"$'\n' == *$'\n'"$ep_no"$'\n'* ]] || die "Invalid episode!"
    [[ "$log_episode" == 1 ]] && logger -t anifuzz "${anime_title} ${ep_no}" 2>/dev/null
    [[ -z "$video_link" ]] && {
        hianime_m3u8 "$ep_no" "$mode" || die "Failed to extract video link!"
        [[ -z "$video_link" ]] && die "No valid sources found for $mode!"
    }
    local player_args=()
    [[ -n "$refr" ]] && player_args+=(--referrer="$refr")
    [[ -n "$sub_link" ]] && player_args+=(--sub-file="$sub_link")
    $player_function $player_extra_flags "${player_args[@]}" --force-media-title="${anime_title} Episode ${ep_no}" "$video_link"
    local mpv_exitcode=$? replay="$video_link"
    unset video_link
    update_history
    [[ "$exit_after_play" == 1 ]] && exit "$mpv_exitcode"
}

# MAIN
mode="${ANI_CLI_MODE:-sub}"
log_episode="${ANI_CLI_LOG:-1}"
player_function="${ANI_CLI_PLAYER:-mpv}"
player_extra_flags="${ANI_CLI_PLAYER_FLAGS:-""}"
exit_after_play="${ANI_CLI_EXIT_AFTER_PLAY:-0}"
menu_extra_flags="${ANI_CLI_MENU_FLAGS:-"-w 70 -l 15"}"
histfile="${ANI_CLI_HIST_DIR:-${XDG_STATE_HOME:-$HOME/.local/state}/anifuzz}/ani-hsts"
mkdir -p "${histfile%/*}"
[[ ! -f "$histfile" ]] && : >"$histfile"
[[ "${1:-}" == "-c" || "${1:-}" == "--continue" ]] && source="history"

for dep in curl fuzzel "$player_function"; do
    command -v "$dep" >/dev/null || die "Program $dep not found. Please install it."
done

# searching
case "$source" in
    history)
        result=$(awk -F'\t' '{printf "%s\t%s (watched ep %s)\n", $2, $3, $1}' "$histfile" | nl -w1 -s"	" | nth "Select anime: ")
        [[ -z "$result" ]] && die "History empty or cancelled!"
        anime_id="${result%%	*}"
        ep_no="${result##*(watched ep }"
        ep_no="${ep_no%)}"
        anime_title="${result#*	}"
        anime_title="${anime_title% (watched ep *}"
        episode_maps="$(hianime_episodes "$anime_id")"
        ep_list="$(cut <<<"$episode_maps" -f 2)"
        
        # Find next episode or fallback to current
        next_ep=$(<<<"$ep_list" sed -n "/^${ep_no}$/{n;p;}") 2>/dev/null
        [[ -n "$next_ep" ]] && ep_no="$next_ep"
        ;;
    *)
        [[ -z "$query" ]] && query=$(fuzzel -d --prompt-only="Search anime: " $menu_extra_flags 2>/dev/null)
        [[ -z "$query" ]] && exit 1
        result=$(hianime_search "${query// /+}" | nl -w1 -s"	" | nth "Select anime: ")
        [[ -z "$result" ]] && die "No results found or cancelled!"
        anime_title="${result#*	}"
        anime_id="${result%%	*}"
        episode_maps="$(hianime_episodes "$anime_id")"
        ep_list="$(cut <<<"$episode_maps" -f 2)"
        ep_no=$(<<<"$ep_list" nth "Select episode: ")
        [[ -z "$ep_no" ]] && exit 1
        ;;
esac

# playback & loop
play

while cmd=$(printf "next\nreplay\nprevious\nselect\nquit" | nth "Playing episode $ep_no of $anime_title... "); do
    case "$cmd" in
        next) ep_no=$(<<<"$ep_list" sed -n "/^${ep_no}$/{n;p;}") 2>/dev/null ;;
        replay) video_link="$replay" ;;
        previous) ep_no=$(<<<"$ep_list" sed -n "/^${ep_no}$/{g;1!p;};h") 2>/dev/null ;;
        select) ep_no=$(<<<"$ep_list" nth "Select episode: ") ;;
        *)
            rm -f "${histfile}.new"
            exit 0
            ;;
    esac
    [[ -z "$ep_no" ]] && die "Out of range"
    play
done

# anifuzz (Forked from ani-cli)
# Copyright (c) 2026 elseawhy
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Original project repository: https://github.com/pystardust/ani-cli
